//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JR
{
    using System;
    using System.Collections.Generic;
    
    public partial class View
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string About { get; set; }
        public string Famaly { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
    }
}
